### ISSUE TITLE
props module is not scoped

### ISSUE THREAD

**Issue by asabil** [TylorS167/mostly-dom#16]
Hi again,

Another difference I noticed between snabbdom and mostly-dom is that the props module is not scoped:

```javascript
// Snabbdom
h('div', {props: {className: 'xyz'}})
```

```javascript
// mostly-dom
h('div', {className: 'xyz'})
```

What is the rationale for not scoping props?

Thanks

**Comment by TylorS** [comment]
Properties are what I personally default to using, so I decided to make them unscoped for convenience. 
Backwards compatibility isn't really a goal of mine.

**Comment by asabil** [comment]
I understand, makes sense. Thanks for the clarification.

**Comment by TylorS** [comment]
No problem! Thanks for your questions.
