### ISSUE TITLE
className is not cleared

### ISSUE THREAD

**Issue by asabil** [TylorS167/mostly-dom#22]
I am experiencing an issue where if:

`vnode0` has a className, and `vnode1` does not have a className in `patch(vnode0, vnode1)`, the  patch function fails to clear the className.

I tried looking at the code, and I think that this needs to be fixed here: https://github.com/TylorS167/mostly-dom/blob/8c6549438c470f01fc6a0de52713ffdfca96d468/src/patchVNode/updateElement.ts#L10

I think the same holds for the ID and scope.

Thanks

**Comment by TylorS** [comment]
Hello @asabil thanks for the issue. Looking at the code now, you're totally right. 
I'll whip together the fix soon

**Comment by TylorS** [comment]
Fixed in v3.6.0

**Comment by asabil** [comment]
Hi @TylorS 
It looks like this issue has been reintroduced with 4.0.0

**Comment by TylorS** [comment]
This should also been fixed with v4.2.0
