### ISSUE TITLE
Hyperscript functions should probably not be too smart about class names

### ISSUE THREAD

**Issue by asabil** [TylorS167/mostly-dom#23]
mostly-dom seems to infer whether a parameter is an actual class name or an ID by looking at its first character, and checking whether it is a `.` or a `#`.

I am not quite certain if this is a wise approach because the following would be non-deterministic:

`div(someUserGeneratedContent)`

it will either produce an empty `div` or a `div` with text content depending on the string value.

**Comment by TylorS** [comment]
It's meant to be a convenience, but I do see the concern. 
However, it's possible to use `div([ someUserGeneratedContent ])` to make it deterministic.

**Comment by asabil** [comment]
Thank you for the prompt reply.

`div([ someUserGeneratedContent ])` would definitely help avoiding the issue. I think, however, that it is quite easy to forget to wrap the value in an array, and introduce a very subtle bug, not as serious as XSS, but very similar in nature.

It would be ideal if `mostly-dom`, given its focus on strong typing information, ensured that such bugs could not occur.

Thanks again.

**Comment by TylorS** [comment]
I've been thinking about it for some time, but just haven't gotten around to it. 
I think that maybe it's okay to remove all of the parsing of selectors and require the use of props when setting className and id. e.g.

```typescript
div({ className: 'className', id: 'id'})
```

This is how I, and everyone at my job make use of them. What do you think?

**Comment by TylorS** [comment]
This would be a breaking change of course. Also, it'd likely have a slightly measurable performance improvement; `parseSelector` is a fairly slow function

**Comment by asabil** [comment]
I think that would be much better: safer, simpler and faster. What not to like 😄 ?

**Comment by TylorS** [comment]
This also means we could also strongly type the values that can be used for the first parameter to `h`
