### ISSUE TITLE
Feature Suggestion: Remove default modules

### ISSUE THREAD

**Issue by TylorS** [TylorS167/mostly-dom#46]
Currently if no parameters are given to `init` a set of default modules are used instead. However, potential conflicts in the ordering of the modules can produce quite unexpected results. Additionally the use of default modules forcing your application to bundle them even when not in use.

I propose that we:

1. Require modules to be explicitly passed in to `init`
2. export a list of the default modules in a documented order to explain possible conflicts

This has the main benefit of allowing more flexibility in giving preference to module ordering. Application bundle size can also be reduced greatly if certain modules are not used and can be effectively tree-shaken.

**Comment by Frikki** [comment]
Shall or shan't?

**Comment by TylorS** [comment]
I think we should

**Comment by TylorS** [comment]
Done in v5
