### ISSUE TITLE
Support Functions as first parameter to `h`

### ISSUE THREAD

**Issue by TylorS** [TylorS167/mostly-dom#50]
```typescript
function myViewFunction(props: MyProps, children: Array<VNode>): VNode {
  return div(props, [ ul(children)  ])
}

h(myViewFunction, myProps, children)
```

**Comment by TylorS** [comment]
cc @frikki

**Comment by Frikki** [comment]
pros and cons?

**Comment by TylorS** [comment]
Basically, It gives us a clean way to support JSX. Cons are the already megamorphic h function

**Comment by Frikki** [comment]
> Cons are the already megamorphic h function

Ha ha ha ha!

> ... It gives us a clean way to support JSX

Which is fine.

How will previous calls like `h('line', ...)` work?

**Comment by TylorS** [comment]
I think they should continue to work the same way. Do you have thoughts on improvements?

**Comment by Frikki** [comment]
Looking at the `h` code, I think there’s room for a lot of improvement. But as with anything, there are trade-offs. In this case, perhaps performance vs readability.

**Comment by TylorS** [comment]
This is done now in v5.0!
